### ISSUE TITLE
Support ISO 8601 via moov-io base.Time

### ISSUE THREAD

**Issue by wadearnold** [moov-io/banktime#5]
Decorate Banktime to support ISO 8601 via  for moov-io [base.Time](https://github.com/moov-io/base/time.go) to be used for calculating the next available payment date.

**Comment by adamdecaf** [comment]
`base.Time` values can be used by grabbing the underlying `time.Time` value, but not very elegantly. 

```go
postDate := banktime.New(base.Now().Time).AddBankingDay(1) // time.Time value, not base.Time
```

Should we augment `base.Time` instead? 

```Go
func (t Time) BankTime() banktime.Time {}

func (t Time) AddBankingDays(n int) banktime.Time {}
```

**Comment by adamdecaf** [comment]
What if we just combined the two libraries? Does banktime need to be separate?

```Go
func (t Time) IsBankingDay() bool 
func (t Time) AddBankingDay(d int) time.Time 
func (t Time) IsWeekend() bool
```

**Comment by wadearnold** [comment]
It was separated because it created a dependency on [cal](github.com/rickar/cal). I didn't have a dependency strategy a year ago.

**Comment by adamdecaf** [comment]
Makes sense. I'd be ok with merging the two libraries together and archiving (make read-only) this repository.

**Comment by wadearnold** [comment]
That sounds good to me. It's basically a fancy validator of sorts.
